### ISSUE TITLE
Document browser connectivity story and roadmap

### ISSUE THREAD

**Issue by BigLep** [libp2p/website#154]
The browser connectivity site has been deployed but there are still many things to be done:

- [ ] Move content out of subdomain (into to a subdirectory)
- [ ] Apply proposed fixes from ["What can be improved?" table](https://www.notion.so/pl-strflt/ed17a1d5b7164d91ab461750549b56d5?v=9d1c810bd7d44951aac23151e568e3c7)
- [ ] Address open items below

---
## Done Criteria
A URL can be shared that answers:
1. How a browser node can connect to other nodes (other browser nodes, other non-browser nodes), accounting for the differences amongst browsers and libp2p implementations.  
2. Sample code making these connections.
3. How to follow along on contribute to the development tracks

If someone isn't aware of the intricacies of this topic or has outdated information, they should be able to start at this resource and quickly learn the options, the options' pros/cons, what's available today, what's coming, how to follow, and how to help.

While not end-user facing, we also need to do the following before marking this as done (or these items should move to a separate item that we also track - we need to make sure we don't drop them just because we get the content done):
- [ ] Having clear documentation on how to update this documentation and some of the design decisions (assuming this is a separate website)
- [ ] Metrics around usage (similar to what we have with docs.ipfs.io)
- [ ] Any other standard SEO low-hanging fruit SEO items
- [ ] Links to it from reasonable places within docs.ipfs.io to help with discoverability
- [ ] Drive traffic using marketing channels (blog post, twitter)

## Why Important
The browser connectivity story has improved over the last couple of years, but there isn't a one-size-fits-all silver-bullet.  We need to help developers understand the landscape so they don't oversimplify or erroneously write-off libp2p.

Not only do we want developers informed, but this is an exciting time when it comes to browser connectivity, and we'd love to capture some of that interest to help develop and test the improvements that are coming.

## User/Customer
Developers using libp2p so they can understand if/where/how libp2p can help them with their browser applications.

## Notes
1. Some of this information is in https://github.com/libp2p/specs/blob/master/connections/hole-punching.md#vision.  Things it doesn't include currently:
 - Status of each transport in each libp2p implementation
 - Browser vendor specifics (e.g., Chromium having WebTranport support)
 - Sample code for getting started
2. This issue was created in the libp2p/docs repo, but that doesn't mean it needs to be solved here.  If this information is authored somewhere else, we should at least have a link from the docs website to it.

**Comment by BigLep** [comment]
@p-shahi : what are your thoughts on timeline for wrapping this up?  I know @DannyS03 is blocked on various reviews for other areas.  In the meantime is this something he can help execute on?  I know we're seeing low visitors and high bounce (per https://www.notion.so/pl-strflt/2023-01-06-IP-Stewards-SitRep-d455db436b0c4aacbdccc2c265f91e67#cd71c07408a34bc5abaab5cc8ec23847 ) and wanted to see what we can to get this to a closeable state.
